# PHP CircleCI 2.0 configuration file

version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8
  percy: percy/agent@0.1.2
jobs:
  setup:
    docker:
        - image: circleci/php:7.2.21-zts-stretch-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - composer-{{ checksum "composer.lock" }}
      - run:
          name: Install PHP dependencies
          command: composer install -o -n --ignore-platform-reqs
      - save_cache:
          key: composer-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NodeJS dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  release-app:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: CIRCLE_PULL_REQUEST_NUMBER
          command: echo ${CIRCLE_PULL_REQUEST##*/}
      - run:
          name: Create Heroku App
          command: heroku apps:info --app $CIRCLE_PROJECT_REPONAME-pr-${CIRCLE_PULL_REQUEST##*/} || heroku apps:create --region eu $CIRCLE_PROJECT_REPONAME-pr-${CIRCLE_PULL_REQUEST##*/}
      - run:
          name: Add App to Heroku pipeline as a Review App.
          command: heroku pipelines:add $CIRCLE_PROJECT_REPONAME -a $CIRCLE_PROJECT_REPONAME-pr-${CIRCLE_PULL_REQUEST##*/} --stage review || exit 0
      - run:
          name: Set host name
          command: heroku config:set HEROKU_APP_NAME=$CIRCLE_PROJECT_REPONAME-pr-${CIRCLE_PULL_REQUEST##*/} --app $CIRCLE_PROJECT_REPONAME-pr-${CIRCLE_PULL_REQUEST##*/}
      - run:
          name: Set server environment
          command: heroku config:set ENV=qa  --app $CIRCLE_PROJECT_REPONAME-pr-${CIRCLE_PULL_REQUEST##*/}
      - run:
          name: Add app’s remote Git repo.
          command: git remote add $CIRCLE_PROJECT_REPONAME-pr-${CIRCLE_PULL_REQUEST##*/} https://heroku:$HEROKU_API_KEY@git.heroku.com/$CIRCLE_PROJECT_REPONAME-pr-${CIRCLE_PULL_REQUEST##*/}.git
      - run:
          name: Push branch to Heroku for deployment.
          command: git push -f $CIRCLE_PROJECT_REPONAME-pr-${CIRCLE_PULL_REQUEST##*/} $CIRCLE_BRANCH:master
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Add app’s remote Git repo.
          command: git remote add $CIRCLE_PROJECT_REPONAME https://heroku:$HEROKU_API_KEY@git.heroku.com/$CIRCLE_PROJECT_REPONAME.git
      - run:
          name: Push branch to Heroku for deployment.
          command: git push -f $CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH:master
  visual-regression:
    executor: percy/finalize_all
    steps:
      - run:
          name: Test Job
          command: echo 'Test Complete'
workflows:
  version: 2
  setup_and_deploy:
    jobs:
      - setup
      - release-app:
          requires:
            - setup
          filters:
            branches:
              ignore:
                - master
      - deploy:
          requires:
            - setup
          filters:
            branches:
              only: master
      - visual-regression:
          requires:
            - setup
            - release-app
          filters:
            branches:
              ignore:
                - master
      - percy/finalize_all:
         requires:
           - visual-regression
